### PR TITLE
Fix the composer install reference.

### PR DESCRIPTION
**Pull request by ChadSikorra**
This updates the composer install references in the readme to install this bundle.

### CODE REVIEW

**Review by Rastusik — CHANGES_REQUESTED** [review]
@ChadSikorra please make this change against the `develop` branch. thank you

**Comment by ChadSikorra** [comment]
Oops, didn't see the develop branch when I did these. I'll rebase both soon. Maybe that'll clear up the CI errors.

**Comment by ChadSikorra** [comment]
Well, I rebased against develop and that at least let Travis run. But the errors in the build are quite strange, and obviously unrelated to a change in the readme 😅

**Comment by Rastusik** [comment]
hi @ChadSikorra , I think I fixed the pipelines. Could you please rebase your commit on the develop branch and wait for the checks to pass? thank you

**Pull request merged**
