### PR TITLE
feat(command): option to keep opened symfony console, to allow use ...

### PR DESCRIPTION
**Pull request by pistej**
...php://stdout

#240

### CODE REVIEW

**Comment by pistej** [comment]
In our app, we use monolog, and main stream handler is configured to send all logs to `php://stderr`, in server start command console output is closed, thus all logs from app are lost, If we keep console open then can see all logs in console.

**Comment by pistej** [comment]
yes, we use :run command for production, staging env and is fine, we use docker, but for local dev and local test env we use docker entrypoint file which also  with `inotifywait` detect file changes and perform server hard/soft reload (commands start, stop, reload) for seamles developer experience, ...  command ;run is not useful since is blocked and waiting for Ctrl+C

**Comment by Rastusik** [comment]
@pistej can you please log in to Circle CI using Github and authorise acces to your forked repository? it seems that the problem with the pipelines only comes from your pull requests, the PRs from dependabot are working after I fixed SSH keys

**Comment by pistej** [comment]
I logged in, project is somehow setup ... but what next? not sure ... do I need run circle ci action in my fork?

**Comment by Rastusik** [comment]
not sure, I'm just seeing this: https://app.circleci.com/pipelines/github/pixelfederation/swoole-bundle/1068
it says that 
```
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.
```

which brings me to the following solution https://support.circleci.com/hc/en-us/articles/12504745606171-Why-am-I-seeing-the-Could-not-find-a-usable-config-yml-you-may-have-revoked-the-CircleCI-OAuth-app-message ... could you try this?

It seems like Circle CI cannot access your forked branch and that is why the CI won't run but I'm not sure, haven't seen this before

**Comment by Rastusik** [comment]
not sure what is wrong here but it seems like the test PR from your colleague works https://github.com/pixelfederation/swoole-bundle/pull/259 ... seems like this has something to do with some of your settings...

**Comment by pistej** [comment]
yea, one different thing is: I'm part of Wesupport.sk organization on github, and can see some of those setting in circleci too, but I was setting all things as me, user.

**Comment by pistej** [comment]
seems started working since I unfollowed/unsetup my fork project from circleci :upside_down_face:

**Comment by Rastusik** [comment]
I'm glad you worked it out! :) I'll look at it and the other PRs hopefully tomorrow

**Comment by Rastusik** [comment]
@pistej I'm currently looking at #252 and correct me if I'm wrong, but it seems unrelated to this PR (except it uses the flag from this PR, but I think the flag and the function is not natural and there could be another way). I'm wondering how hard would it be to decouple the console output from the actual logger for your specific use case to work. Since you are using docker, how about setting `tty: true` and setting monolog to output logs to `/dev/console` ? this way the SF app should be able tou output logs into docker console output stream even with standard console output closed, at least I think so.

Could you please try this monolog config? 

```yaml
monolog:
  handlers:
    main:
      type: stream
      path: '/dev/console'
```

Don't forget to set tty to true to your docker compose

**Comment by pistej** [comment]
hmm ... this feature has more to do with #261 not with #252 ?!

**Comment by Rastusik** [comment]
Probably, I didn't have time to look on #262 . I'll take a look and we will see.

**Comment by Rastusik** [comment]
@pistej I reviewed #261 and, well, you are probably right about #261 but this PR still doesn't make any sense if the doctrine logger is working, does it?

**Comment by Rastusik** [comment]
that's great to hear!!! :)  can you please describe how you did it for the sake of future generations? :) maybe it would be helpful for other people.

**Comment by pistej** [comment]
base monolog setting:
```yaml
monolog:
  channels: [ 'swoole.access_log' ]
  handlers:
    main:
      type: fingers_crossed
      action_level: info
      handler: stderr
      channels: [ '!event', "!php", "!request" ]

    stderr:
      type: stream
      path: "php://stderr"
      level: info

    # set higher priority and `bubble: false` to handle access logs only by this handler and stop propagation
    # type: stream (in same way as stderr) is not working, so we use `handler: stderr`
    swoole_access_log:
      type: fingers_crossed
      action_level: info
      handler: stderr
      channels: 'swoole.access_log'
      bubble: false
      priority: 110
#      formatter: monolog.formatter.line.swoole.access_log
```

**Comment by Rastusik** [comment]
thank you!

**Pull request closed without merging**
