### PR TITLE
Feature: #238 added WorkerStop, WorkerError WorkerExitHandler

### PR DESCRIPTION
**Pull request by pistej**
#238

### CODE REVIEW

**Comment by Rastusik** [comment]
@pistej I don't really know what is wrong with the pipeline, will need to investigate later

**Comment by Rastusik** [comment]
@pistej it seems like there was a bug with CircleCI... When I closed and reopened the PR the CI pipeline started correctly. Please fix the issues from the pipeline to continue with the process (commit message needs to be in conventonal commit format - https://www.conventionalcommits.org/en/v1.0.0/ )

**Comment by pistej** [comment]
@Rastusik rdy from my side

**Review by Rastusik — APPROVED** [review]

**Comment by pistej** [comment]
done

**Pull request merged**
